// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClIBtxLPwYAa0C_rp5phd8cBlshGhdqk8',
    appId: '1:958295250515:web:2e7301975d329b696cd8a6',
    messagingSenderId: '958295250515',
    projectId: 'zoom-clone-fd342',
    authDomain: 'zoom-clone-fd342.firebaseapp.com',
    storageBucket: 'zoom-clone-fd342.appspot.com',
    measurementId: 'G-SZT43Q5YYX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRB6cDdBp_Izfxwlr2XgCPr2LfmrxvEnE',
    appId: '1:958295250515:android:f5672fa9e3e981cb6cd8a6',
    messagingSenderId: '958295250515',
    projectId: 'zoom-clone-fd342',
    storageBucket: 'zoom-clone-fd342.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDptIllYQfYbNHkmGICZR8uq6WU5-IhASY',
    appId: '1:958295250515:ios:0af91a952d10e8b96cd8a6',
    messagingSenderId: '958295250515',
    projectId: 'zoom-clone-fd342',
    storageBucket: 'zoom-clone-fd342.appspot.com',
    iosClientId: '958295250515-hdcefpr74sgof6ad93p1na6gmdbefe0u.apps.googleusercontent.com',
    iosBundleId: 'com.example.zoomClone',
  );
}
